/*
* Generated file
*
* Generated from: yang module name: hello-impl yang module local name: hello-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed May 25 12:05:08 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.hello.impl;
public interface HelloImplModuleMXBean {
    public javax.management.ObjectName getRpcRegistry();

    /**
    * wires in the RPC registry service
    */
    public void setRpcRegistry(javax.management.ObjectName rpcRegistry);

    public javax.management.ObjectName getDataBroker();

    /**
    * wires in the data broker registry service
    */
    public void setDataBroker(javax.management.ObjectName dataBroker);

    public javax.management.ObjectName getBindingRegistry();

    /**
    * wires in the binding broker osgi service
    */
    public void setBindingRegistry(javax.management.ObjectName bindingRegistry);

}
