/*
* Generated file
*
* Generated from: yang module name: hello-impl yang module local name: hello-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu May 19 15:42:55 CST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.hello.impl;
public class HelloImplModuleFactory extends org.opendaylight.controller.config.yang.config.hello.impl.AbstractHelloImplModuleFactory {

}
